coverage:
  status:
    patch:
      default:
        target: 90%
        threshold: 1%
  precision: 2

ignore:
  - "lib/src/**/*.g.dart"

comment:
  layout: "reach, diff, flags, files"
  behavior: new
