coverage:
  status:
    # pull-requests only
    patch:
      default:
        threshold: 1%
  precision: 2
  round: down
  range: "90...100"

ignore:
  - "lib/src/**/*.g.dart"

comment:
  layout: "reach, diff, flags, files"
  behavior: new
