name: pharmaceutical_datamatrix
description: Model to parse and create pharmaceutical datamatrix data
version: 0.1.0
homepage: https://santetis.fr
author: Kevin Segaud <kevin@santetis.fr>

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  pedantic: ^1.8.0
  meta: ^1.1.8
  intl: ^0.16.0

dev_dependencies:
  test: ^1.6.0
