name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_and_coverage:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: pub get
      - name: Dart analyze
        run: dartanalyzer --options=analysis_options.yaml --fatal-hints --fatal-warnings .
      - name: Run tests
        run: pub run test
      - name: Generating coverage
        run: tools/generate_coverage.sh
      - uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}} #required
          file: ./coverage/lcov.info
